package io.scalaland.endpoints.elm.emit

import io.scalaland.endpoints.elm.BuildInfo

object Commons {

  val headerComment: String =
    s"""{-
      |  This file was generated by endpoints-elm ${BuildInfo.version} interpreter.
      |  Do not edit this file manually.
      |
      |  See https://github.com/scalalandio/endpoints-elm for more information.
      |-}
      |""".stripMargin

}
