package io.scalaland.endpoints.elm.emit

object Commons {

  val headerComment: String =
    """{-
      |  This file was generated by endpoints-elm interpreter.
      |  Do not edit this file manually.
      |
      |  See https://github.com/scalalandio/endpoints-elm for more information.
      |-}
      |""".stripMargin

}
