{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Url.QueryParams exposing (..)

import Url.Builder
import Bool.Extra
import Maybe.Extra


import Date exposing (..)
import Uuid exposing (..)


stringGet : String -> String
stringGet string =
  Url.Builder.relative
    ["/", "string"]
    ([Url.Builder.string "string" ( string)])


intGet : Int -> String
intGet int =
  Url.Builder.relative
    ["/", "int"]
    ([Url.Builder.int "int" int])


longGet : Int -> String
longGet long =
  Url.Builder.relative
    ["/", "long"]
    ([Url.Builder.int "long" long])


doubleGet : Float -> String
doubleGet double =
  Url.Builder.relative
    ["/", "double"]
    ([Url.Builder.string "double" (String.fromFloat double)])


boolGet : Bool -> String
boolGet bool =
  Url.Builder.relative
    ["/", "bool"]
    ([Url.Builder.string "bool" ((String.toLower << Bool.Extra.toString) bool)])


uuidGet : Uuid -> String
uuidGet uuid =
  Url.Builder.relative
    ["/", "uuid"]
    ([Url.Builder.string "uuid" (Uuid.toString uuid)])


dateGet : Date -> String
dateGet date =
  Url.Builder.relative
    ["/", "date"]
    ([Url.Builder.string "date" (Date.toIsoString date)])


listGet : (List Int) -> String
listGet value =
  Url.Builder.relative
    ["/", "list"]
    ((value |> List.map (\p -> Url.Builder.string "value" (String.fromInt p))))


optionGet : (Maybe Int) -> String
optionGet value =
  Url.Builder.relative
    ["/", "option"]
    ((value |> Maybe.map (\p -> Url.Builder.string "value" (String.fromInt p)) |> Maybe.Extra.toList))


manyparamsGet : Int -> Float -> String
manyparamsGet intValue dblValue =
  Url.Builder.relative
    ["/", "many-params"]
    ([Url.Builder.int "intValue" intValue] ++ [Url.Builder.string "dblValue" (String.fromFloat dblValue)])

