{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Requests exposing (..)

import Request.Url.Requests
import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Data.Coproduct exposing (..)
import Data.Foo exposing (..)
import Date exposing (..)
import Uuid exposing (..)


jsonstringPost : String -> RequestBuilder ()
jsonstringPost string =
  HttpBuilder.post (Request.Url.Requests.jsonstringPost )
    |> HttpBuilder.withJsonBody (Encode.string  string)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonintPost : Int -> RequestBuilder ()
jsonintPost int =
  HttpBuilder.post (Request.Url.Requests.jsonintPost )
    |> HttpBuilder.withJsonBody (Encode.int  int)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonlongPost : Int -> RequestBuilder ()
jsonlongPost int =
  HttpBuilder.post (Request.Url.Requests.jsonlongPost )
    |> HttpBuilder.withJsonBody (Encode.int  int)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonfloatPost : Float -> RequestBuilder ()
jsonfloatPost float =
  HttpBuilder.post (Request.Url.Requests.jsonfloatPost )
    |> HttpBuilder.withJsonBody (Encode.float  float)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsondoublePost : Float -> RequestBuilder ()
jsondoublePost float =
  HttpBuilder.post (Request.Url.Requests.jsondoublePost )
    |> HttpBuilder.withJsonBody (Encode.float  float)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonbooleanPost : Bool -> RequestBuilder ()
jsonbooleanPost bool =
  HttpBuilder.post (Request.Url.Requests.jsonbooleanPost )
    |> HttpBuilder.withJsonBody (Encode.bool  bool)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonuuidPost : Uuid -> RequestBuilder ()
jsonuuidPost uuid =
  HttpBuilder.post (Request.Url.Requests.jsonuuidPost )
    |> HttpBuilder.withJsonBody (Uuid.encode  uuid)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsondatePost : Date -> RequestBuilder ()
jsondatePost date =
  HttpBuilder.post (Request.Url.Requests.jsondatePost )
    |> HttpBuilder.withJsonBody ((Encode.string << Date.toIsoString)  date)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsoncaseclassPost : Foo -> RequestBuilder ()
jsoncaseclassPost foo =
  HttpBuilder.post (Request.Url.Requests.jsoncaseclassPost )
    |> HttpBuilder.withJsonBody (Data.Foo.encoder  foo)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsoncoproductPost : Coproduct -> RequestBuilder ()
jsoncoproductPost coproduct =
  HttpBuilder.post (Request.Url.Requests.jsoncoproductPost )
    |> HttpBuilder.withJsonBody (Data.Coproduct.encoder  coproduct)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonlistPost : (List String) -> RequestBuilder ()
jsonlistPost list =
  HttpBuilder.post (Request.Url.Requests.jsonlistPost )
    |> HttpBuilder.withJsonBody ((Encode.list Encode.string )  list)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


jsonmapPost : (Dict String Foo) -> RequestBuilder ()
jsonmapPost dict =
  HttpBuilder.post (Request.Url.Requests.jsonmapPost )
    |> HttpBuilder.withJsonBody ((Encode.dict identity (Data.Foo.encoder ) ) dict)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000

