{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Url.Counter exposing (..)

import Url.Builder
import Bool.Extra
import Maybe.Extra





currentvalueGet : String
currentvalueGet  =
  Url.Builder.relative
    ["/", "current-value"]
    ([])


incrementPost : String
incrementPost  =
  Url.Builder.relative
    ["/", "increment"]
    ([])

