{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Segments exposing (..)

import Request.Url.Segments
import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Date exposing (..)
import Uuid exposing (..)


stringStringGet : String -> RequestBuilder ()
stringStringGet string =
  HttpBuilder.get (Request.Url.Segments.stringStringGet string)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


intIntGet : Int -> RequestBuilder ()
intIntGet int =
  HttpBuilder.get (Request.Url.Segments.intIntGet int)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


longLongGet : Int -> RequestBuilder ()
longLongGet long =
  HttpBuilder.get (Request.Url.Segments.longLongGet long)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


uuidUuidGet : Uuid -> RequestBuilder ()
uuidUuidGet uuid =
  HttpBuilder.get (Request.Url.Segments.uuidUuidGet uuid)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


dateDateGet : Date -> RequestBuilder ()
dateDateGet date =
  HttpBuilder.get (Request.Url.Segments.dateDateGet date)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000

