{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Segments exposing (..)

import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Date exposing (..)
import Uuid exposing (..)


stringStringGet : String -> RequestBuilder ()
stringStringGet string =
  HttpBuilder.get ("/string/" ++ string)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


intIntGet : Int -> RequestBuilder ()
intIntGet int =
  HttpBuilder.get ("/int/" ++ String.fromInt int)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


longLongGet : Int -> RequestBuilder ()
longLongGet long =
  HttpBuilder.get ("/long/" ++ String.fromInt long)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


uuidUuidGet : Uuid -> RequestBuilder ()
uuidUuidGet uuid =
  HttpBuilder.get ("/uuid/" ++ Uuid.toString uuid)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


dateDateGet : Date -> RequestBuilder ()
dateDateGet date =
  HttpBuilder.get ("/date/" ++ Date.toIsoString date)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000
