{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Counter exposing (..)

import Request.Url.Counter
import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Data.Counter exposing (..)
import Data.Increment exposing (..)


currentvalueGet : RequestBuilder Counter
currentvalueGet  =
  HttpBuilder.get (Request.Url.Counter.currentvalueGet )
    |> HttpBuilder.withExpectJson Data.Counter.decoder
    |> HttpBuilder.withTimeout 30000


incrementPost : Increment -> RequestBuilder ()
incrementPost increment =
  HttpBuilder.post (Request.Url.Counter.incrementPost )
    |> HttpBuilder.withJsonBody (Data.Increment.encoder  increment)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000

