{-
  This file was generated by endpoints-elm 0.10.0 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Counter exposing (..)

import Request.Url.Counter
import Http
import HttpBuilder.Task exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Bytes exposing (Bytes)
import Dict exposing (Dict)

import Data.Counter exposing (..)
import Data.Increment exposing (..)
import EndpointsElm


currentvalueGet : RequestBuilder Http.Error Counter
currentvalueGet  =
  HttpBuilder.Task.get (Request.Url.Counter.currentvalueGet )
    |> HttpBuilder.Task.withResolver (Http.stringResolver (EndpointsElm.httpResolveJson (Data.Counter.decoder)))
    |> HttpBuilder.Task.withTimeout 30000


incrementPost : Increment -> RequestBuilder Http.Error ()
incrementPost increment =
  HttpBuilder.Task.post (Request.Url.Counter.incrementPost )
    |> HttpBuilder.Task.withBody (Http.jsonBody (Data.Increment.encoder increment))
    |> HttpBuilder.Task.withResolver (Http.stringResolver (EndpointsElm.httpResolveUnit))
    |> HttpBuilder.Task.withTimeout 30000

