{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.QueryParams exposing (..)

import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra

import Date exposing (..)
import Uuid exposing (..)


stringGet : String -> RequestBuilder ()
stringGet string =
  HttpBuilder.get "/string"
    |> HttpBuilder.withQueryParams ([("string",  string)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


intGet : Int -> RequestBuilder ()
intGet int =
  HttpBuilder.get "/int"
    |> HttpBuilder.withQueryParams ([("int", String.fromInt int)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


longGet : Int -> RequestBuilder ()
longGet long =
  HttpBuilder.get "/long"
    |> HttpBuilder.withQueryParams ([("long", String.fromInt long)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


doubleGet : Float -> RequestBuilder ()
doubleGet double =
  HttpBuilder.get "/double"
    |> HttpBuilder.withQueryParams ([("double", toString double)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


boolGet : Bool -> RequestBuilder ()
boolGet bool =
  HttpBuilder.get "/bool"
    |> HttpBuilder.withQueryParams ([("bool", (String.toLower << Bool.Extra.toString) bool)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


uuidGet : Uuid -> RequestBuilder ()
uuidGet uuid =
  HttpBuilder.get "/uuid"
    |> HttpBuilder.withQueryParams ([("uuid", Uuid.toString uuid)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


dateGet : Date -> RequestBuilder ()
dateGet date =
  HttpBuilder.get "/date"
    |> HttpBuilder.withQueryParams ([("date", Date.toIsoString date)])
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000
