{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.QueryParams exposing (..)

import Request.Url.QueryParams
import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Date exposing (..)
import Uuid exposing (..)


stringGet : String -> RequestBuilder ()
stringGet string =
  HttpBuilder.get (Request.Url.QueryParams.stringGet string)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


intGet : Int -> RequestBuilder ()
intGet int =
  HttpBuilder.get (Request.Url.QueryParams.intGet int)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


longGet : Int -> RequestBuilder ()
longGet long =
  HttpBuilder.get (Request.Url.QueryParams.longGet long)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


doubleGet : Float -> RequestBuilder ()
doubleGet double =
  HttpBuilder.get (Request.Url.QueryParams.doubleGet double)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


boolGet : Bool -> RequestBuilder ()
boolGet bool =
  HttpBuilder.get (Request.Url.QueryParams.boolGet bool)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


uuidGet : Uuid -> RequestBuilder ()
uuidGet uuid =
  HttpBuilder.get (Request.Url.QueryParams.uuidGet uuid)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


dateGet : Date -> RequestBuilder ()
dateGet date =
  HttpBuilder.get (Request.Url.QueryParams.dateGet date)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


listGet : (List Int) -> RequestBuilder ()
listGet value =
  HttpBuilder.get (Request.Url.QueryParams.listGet value)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


optionGet : (Maybe Int) -> RequestBuilder ()
optionGet value =
  HttpBuilder.get (Request.Url.QueryParams.optionGet value)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


manyparamsGet : Int -> Float -> RequestBuilder ()
manyparamsGet intValue dblValue =
  HttpBuilder.get (Request.Url.QueryParams.manyparamsGet intValue dblValue)
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000

