{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Responses exposing (..)

import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Json.Encode as Encode
import Bool.Extra
import Maybe.Extra
import Dict exposing (Dict)

import Data.Coproduct exposing (..)
import Data.Foo exposing (..)
import Date exposing (..)
import Uuid exposing (..)


jsonstringGet : RequestBuilder String
jsonstringGet  =
  HttpBuilder.get "/json-string"
    |> HttpBuilder.withExpectJson Decode.string
    |> HttpBuilder.withTimeout 30000


jsonintGet : RequestBuilder Int
jsonintGet  =
  HttpBuilder.get "/json-int"
    |> HttpBuilder.withExpectJson Decode.int
    |> HttpBuilder.withTimeout 30000


jsonlongGet : RequestBuilder Int
jsonlongGet  =
  HttpBuilder.get "/json-long"
    |> HttpBuilder.withExpectJson Decode.int
    |> HttpBuilder.withTimeout 30000


jsonfloatGet : RequestBuilder Float
jsonfloatGet  =
  HttpBuilder.get "/json-float"
    |> HttpBuilder.withExpectJson Decode.float
    |> HttpBuilder.withTimeout 30000


jsondoubleGet : RequestBuilder Float
jsondoubleGet  =
  HttpBuilder.get "/json-double"
    |> HttpBuilder.withExpectJson Decode.float
    |> HttpBuilder.withTimeout 30000


jsonbooleanGet : RequestBuilder Bool
jsonbooleanGet  =
  HttpBuilder.get "/json-boolean"
    |> HttpBuilder.withExpectJson Decode.bool
    |> HttpBuilder.withTimeout 30000


jsonuuidGet : RequestBuilder Uuid
jsonuuidGet  =
  HttpBuilder.get "/json-uuid"
    |> HttpBuilder.withExpectJson Uuid.decoder
    |> HttpBuilder.withTimeout 30000


jsondateGet : RequestBuilder Date
jsondateGet  =
  HttpBuilder.get "/json-date"
    |> HttpBuilder.withExpectJson (Decode.string |> Decode.andThen (Date.fromIsoString >> Result.map Decode.succeed >> Result.withDefault (Decode.fail "can't parse the date!")))
    |> HttpBuilder.withTimeout 30000


jsoncaseclassGet : RequestBuilder Foo
jsoncaseclassGet  =
  HttpBuilder.get "/json-case-class"
    |> HttpBuilder.withExpectJson Data.Foo.decoder
    |> HttpBuilder.withTimeout 30000


jsoncoproductGet : RequestBuilder Coproduct
jsoncoproductGet  =
  HttpBuilder.get "/json-coproduct"
    |> HttpBuilder.withExpectJson Data.Coproduct.decoder
    |> HttpBuilder.withTimeout 30000


jsonlistGet : RequestBuilder (List String)
jsonlistGet  =
  HttpBuilder.get "/json-list"
    |> HttpBuilder.withExpectJson (Decode.list Decode.string)
    |> HttpBuilder.withTimeout 30000


jsonmapGet : RequestBuilder (Dict String Foo)
jsonmapGet  =
  HttpBuilder.get "/json-map"
    |> HttpBuilder.withExpectJson (Decode.dict Data.Foo.decoder)
    |> HttpBuilder.withTimeout 30000
