{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Data.io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time exposing (..)

import TimeOnly exposing (..)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time = 
  { value : TimeOnly
  , msg : String
  }

init : io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
init = 
  { value = TimeOnly.init
  , msg = ""
  }

decoder : Decoder io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
decoder = Decode.succeed io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
  |> required "value" TimeOnly.decoder 
  |> required "msg" Decode.string 

encoder : io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> Encode.Value
encoder model = Encode.object (fieldsEncoder model)

encoderTagged : (String, String) -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> Encode.Value
encoderTagged (discriminator, tag) model = Encode.object ((discriminator, Encode.string tag) :: fieldsEncoder model)

fieldsEncoder : io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> List (String, Encode.Value)
fieldsEncoder model = 
  [ ( "value", TimeOnly.encoder model.value )
  , ( "msg", Encode.string model.msg )
  ]

setValue : TimeOnly -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
setValue newValue io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time =
  { io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time | value = newValue }
setMsg : String -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
setMsg newMsg io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time =
  { io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time | msg = newMsg }

updateValue : (TimeOnly -> TimeOnly) -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
updateValue f io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time =
  { io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time | value = f io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time.value }
updateMsg : (String -> String) -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time -> io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time
updateMsg f io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time =
  { io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time | msg = f io.scalaland.endpoints.elm.BasicTypeTest.Domain.TimeOrID.Time.msg }