{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Data.TimeOrID exposing (..)

import Data.ID exposing (..)
import Data.Time exposing (..)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type TimeOrID
  = TimeOrIDIDType ID
  | TimeOrIDTimeType Time

init : TimeOrID
init = TimeOrIDIDType Data.ID.init

decoder : Decoder TimeOrID
decoder = Decode.field "type" Decode.string
  |> Decode.andThen decoderTagged

decoderTagged : String -> Decoder TimeOrID
decoderTagged tag = case tag of
  "ID" ->
    Decode.map TimeOrIDIDType Data.ID.decoder

  "Time" ->
    Decode.map TimeOrIDTimeType Data.Time.decoder

  _ ->
    Decode.fail <| "Trying to decode TimeOrID, but type " ++ tag ++ " is not supported!"

encoder : TimeOrID -> Encode.Value
encoder model = case model of
  TimeOrIDIDType id ->
    Data.ID.encoderTagged ("type", "ID" ) id

  TimeOrIDTimeType time ->
    Data.Time.encoderTagged ("type", "Time" ) time




