{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.BasicType exposing (..)

import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Bool.Extra
import Maybe.Extra

import Uuid exposing (..)


unitechoGet : RequestBuilder ()
unitechoGet  =
  HttpBuilder.get "/unit-echo"
    |> HttpBuilder.withExpect (Http.expectStringResponse (\_ -> Ok ()))
    |> HttpBuilder.withTimeout 30000


stringechoGet : String -> RequestBuilder String
stringechoGet  =
  HttpBuilder.get ("/string-echo/" ++ )
    |> HttpBuilder.withExpectJson Decode.string
    |> HttpBuilder.withTimeout 30000


intechoGet : Int -> RequestBuilder Int
intechoGet  =
  HttpBuilder.get ("/int-echo/" ++ String.fromInt )
    |> HttpBuilder.withExpectJson Decode.int
    |> HttpBuilder.withTimeout 30000


longechoGet : Int -> RequestBuilder Int
longechoGet  =
  HttpBuilder.get ("/long-echo/" ++ String.fromInt )
    |> HttpBuilder.withExpectJson Decode.int
    |> HttpBuilder.withTimeout 30000


floatechoGet : String -> RequestBuilder Float
floatechoGet  =
  HttpBuilder.get ("/float-echo/" ++ )
    |> HttpBuilder.withExpectJson Decode.float
    |> HttpBuilder.withTimeout 30000


doubleechoGet : String -> RequestBuilder Float
doubleechoGet  =
  HttpBuilder.get ("/double-echo/" ++ )
    |> HttpBuilder.withExpectJson Decode.float
    |> HttpBuilder.withTimeout 30000


booleanechoGet : String -> RequestBuilder Bool
booleanechoGet  =
  HttpBuilder.get ("/boolean-echo/" ++ )
    |> HttpBuilder.withExpectJson Decode.bool
    |> HttpBuilder.withTimeout 30000


uuidechoGet : Uuid -> RequestBuilder Uuid
uuidechoGet  =
  HttpBuilder.get ("/uuid-echo/" ++ Uuid.toString )
    |> HttpBuilder.withExpectJson Uuid.decoder
    |> HttpBuilder.withTimeout 30000

