{-
  This file was generated by endpoints-elm interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.ProductCoproduct exposing (..)

import Http
import HttpBuilder exposing (RequestBuilder)
import Json.Decode as Decode
import Bool.Extra
import Maybe.Extra

import Data.DateOrUuid exposing (..)


dateoridechoPost : DateOrUuid -> RequestBuilder DateOrUuid
dateoridechoPost dateOrUuid =
  HttpBuilder.post "/DateOrIDEcho"
    |> HttpBuilder.withJsonBody (Data.DateOrUuid.encoder  dateOrUuid)
    |> HttpBuilder.withExpectJson Data.DateOrUuid.decoder
    |> HttpBuilder.withTimeout 30000
