{-
  This file was generated by endpoints-elm 0.9.2 interpreter.
  Do not edit this file manually.

  See https://github.com/scalalandio/endpoints-elm for more information.
-}

module Request.Url.Segments exposing (..)

import Url.Builder
import Bool.Extra
import Maybe.Extra


import Date exposing (..)
import Uuid exposing (..)


stringStringGet : String -> String
stringStringGet string =
  Url.Builder.relative
    ["/", "string", string]
    ([])


intIntGet : Int -> String
intIntGet int =
  Url.Builder.relative
    ["/", "int", String.fromInt int]
    ([])


longLongGet : Int -> String
longLongGet long =
  Url.Builder.relative
    ["/", "long", String.fromInt long]
    ([])


uuidUuidGet : Uuid -> String
uuidUuidGet uuid =
  Url.Builder.relative
    ["/", "uuid", Uuid.toString uuid]
    ([])


dateDateGet : Date -> String
dateDateGet date =
  Url.Builder.relative
    ["/", "date", Date.toIsoString date]
    ([])

